// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package com.example.proto;

public final class Transaction {
  private Transaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SmallTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SmallTransaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 data = 2;</code>
     * @return The data.
     */
    int getData();
  }
  /**
   * Protobuf type {@code SmallTransaction}
   */
  public static final class SmallTransaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SmallTransaction)
      SmallTransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmallTransaction.newBuilder() to construct.
    private SmallTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmallTransaction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SmallTransaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmallTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              data_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Transaction.internal_static_SmallTransaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Transaction.internal_static_SmallTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Transaction.SmallTransaction.class, com.example.proto.Transaction.SmallTransaction.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private int data_;
    /**
     * <code>int32 data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public int getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (data_ != 0) {
        output.writeInt32(2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (data_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Transaction.SmallTransaction)) {
        return super.equals(obj);
      }
      com.example.proto.Transaction.SmallTransaction other = (com.example.proto.Transaction.SmallTransaction) obj;

      if (getId()
          != other.getId()) return false;
      if (getData()
          != other.getData()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Transaction.SmallTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.SmallTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.SmallTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Transaction.SmallTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SmallTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SmallTransaction)
        com.example.proto.Transaction.SmallTransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Transaction.internal_static_SmallTransaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Transaction.internal_static_SmallTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Transaction.SmallTransaction.class, com.example.proto.Transaction.SmallTransaction.Builder.class);
      }

      // Construct using com.example.proto.Transaction.SmallTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        data_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Transaction.internal_static_SmallTransaction_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Transaction.SmallTransaction getDefaultInstanceForType() {
        return com.example.proto.Transaction.SmallTransaction.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Transaction.SmallTransaction build() {
        com.example.proto.Transaction.SmallTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Transaction.SmallTransaction buildPartial() {
        com.example.proto.Transaction.SmallTransaction result = new com.example.proto.Transaction.SmallTransaction(this);
        result.id_ = id_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Transaction.SmallTransaction) {
          return mergeFrom((com.example.proto.Transaction.SmallTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Transaction.SmallTransaction other) {
        if (other == com.example.proto.Transaction.SmallTransaction.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getData() != 0) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Transaction.SmallTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Transaction.SmallTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int data_ ;
      /**
       * <code>int32 data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public int getData() {
        return data_;
      }
      /**
       * <code>int32 data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(int value) {
        
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SmallTransaction)
    }

    // @@protoc_insertion_point(class_scope:SmallTransaction)
    private static final com.example.proto.Transaction.SmallTransaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Transaction.SmallTransaction();
    }

    public static com.example.proto.Transaction.SmallTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SmallTransaction>
        PARSER = new com.google.protobuf.AbstractParser<SmallTransaction>() {
      @java.lang.Override
      public SmallTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmallTransaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmallTransaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmallTransaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Transaction.SmallTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MediumTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MediumTransaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>repeated bytes data = 2;</code>
     * @return A list containing the data.
     */
    java.util.List<com.google.protobuf.ByteString> getDataList();
    /**
     * <code>repeated bytes data = 2;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated bytes data = 2;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    com.google.protobuf.ByteString getData(int index);
  }
  /**
   * Protobuf type {@code MediumTransaction}
   */
  public static final class MediumTransaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MediumTransaction)
      MediumTransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediumTransaction.newBuilder() to construct.
    private MediumTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediumTransaction() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MediumTransaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MediumTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Transaction.internal_static_MediumTransaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Transaction.internal_static_MediumTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Transaction.MediumTransaction.class, com.example.proto.Transaction.MediumTransaction.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> data_;
    /**
     * <code>repeated bytes data = 2;</code>
     * @return A list containing the data.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated bytes data = 2;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated bytes data = 2;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public com.google.protobuf.ByteString getData(int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeBytes(2, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Transaction.MediumTransaction)) {
        return super.equals(obj);
      }
      com.example.proto.Transaction.MediumTransaction other = (com.example.proto.Transaction.MediumTransaction) obj;

      if (getId()
          != other.getId()) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Transaction.MediumTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.MediumTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.MediumTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Transaction.MediumTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MediumTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MediumTransaction)
        com.example.proto.Transaction.MediumTransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Transaction.internal_static_MediumTransaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Transaction.internal_static_MediumTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Transaction.MediumTransaction.class, com.example.proto.Transaction.MediumTransaction.Builder.class);
      }

      // Construct using com.example.proto.Transaction.MediumTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Transaction.internal_static_MediumTransaction_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Transaction.MediumTransaction getDefaultInstanceForType() {
        return com.example.proto.Transaction.MediumTransaction.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Transaction.MediumTransaction build() {
        com.example.proto.Transaction.MediumTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Transaction.MediumTransaction buildPartial() {
        com.example.proto.Transaction.MediumTransaction result = new com.example.proto.Transaction.MediumTransaction(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        if (((bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Transaction.MediumTransaction) {
          return mergeFrom((com.example.proto.Transaction.MediumTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Transaction.MediumTransaction other) {
        if (other == com.example.proto.Transaction.MediumTransaction.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Transaction.MediumTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Transaction.MediumTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<com.google.protobuf.ByteString>(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @return A list containing the data.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDataList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(data_) : data_;
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public com.google.protobuf.ByteString getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MediumTransaction)
    }

    // @@protoc_insertion_point(class_scope:MediumTransaction)
    private static final com.example.proto.Transaction.MediumTransaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Transaction.MediumTransaction();
    }

    public static com.example.proto.Transaction.MediumTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MediumTransaction>
        PARSER = new com.google.protobuf.AbstractParser<MediumTransaction>() {
      @java.lang.Override
      public MediumTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MediumTransaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MediumTransaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediumTransaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Transaction.MediumTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LargeTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LargeTransaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    java.util.List<com.example.proto.Transaction.LargeTransaction.Row> 
        getMatrixList();
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    com.example.proto.Transaction.LargeTransaction.Row getMatrix(int index);
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    int getMatrixCount();
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    java.util.List<? extends com.example.proto.Transaction.LargeTransaction.RowOrBuilder> 
        getMatrixOrBuilderList();
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    com.example.proto.Transaction.LargeTransaction.RowOrBuilder getMatrixOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code LargeTransaction}
   */
  public static final class LargeTransaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LargeTransaction)
      LargeTransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LargeTransaction.newBuilder() to construct.
    private LargeTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LargeTransaction() {
      matrix_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LargeTransaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LargeTransaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                matrix_ = new java.util.ArrayList<com.example.proto.Transaction.LargeTransaction.Row>();
                mutable_bitField0_ |= 0x00000001;
              }
              matrix_.add(
                  input.readMessage(com.example.proto.Transaction.LargeTransaction.Row.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          matrix_ = java.util.Collections.unmodifiableList(matrix_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.proto.Transaction.internal_static_LargeTransaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.proto.Transaction.internal_static_LargeTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.proto.Transaction.LargeTransaction.class, com.example.proto.Transaction.LargeTransaction.Builder.class);
    }

    public interface RowOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LargeTransaction.Row)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated double row = 1;</code>
       * @return A list containing the row.
       */
      java.util.List<java.lang.Double> getRowList();
      /**
       * <code>repeated double row = 1;</code>
       * @return The count of row.
       */
      int getRowCount();
      /**
       * <code>repeated double row = 1;</code>
       * @param index The index of the element to return.
       * @return The row at the given index.
       */
      double getRow(int index);
    }
    /**
     * Protobuf type {@code LargeTransaction.Row}
     */
    public static final class Row extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:LargeTransaction.Row)
        RowOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Row.newBuilder() to construct.
      private Row(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Row() {
        row_ = emptyDoubleList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Row();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Row(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  row_ = newDoubleList();
                  mutable_bitField0_ |= 0x00000001;
                }
                row_.addDouble(input.readDouble());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                  row_ = newDoubleList();
                  mutable_bitField0_ |= 0x00000001;
                }
                while (input.getBytesUntilLimit() > 0) {
                  row_.addDouble(input.readDouble());
                }
                input.popLimit(limit);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            row_.makeImmutable(); // C
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Transaction.internal_static_LargeTransaction_Row_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Transaction.internal_static_LargeTransaction_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Transaction.LargeTransaction.Row.class, com.example.proto.Transaction.LargeTransaction.Row.Builder.class);
      }

      public static final int ROW_FIELD_NUMBER = 1;
      private com.google.protobuf.Internal.DoubleList row_;
      /**
       * <code>repeated double row = 1;</code>
       * @return A list containing the row.
       */
      @java.lang.Override
      public java.util.List<java.lang.Double>
          getRowList() {
        return row_;
      }
      /**
       * <code>repeated double row = 1;</code>
       * @return The count of row.
       */
      public int getRowCount() {
        return row_.size();
      }
      /**
       * <code>repeated double row = 1;</code>
       * @param index The index of the element to return.
       * @return The row at the given index.
       */
      public double getRow(int index) {
        return row_.getDouble(index);
      }
      private int rowMemoizedSerializedSize = -1;

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (getRowList().size() > 0) {
          output.writeUInt32NoTag(10);
          output.writeUInt32NoTag(rowMemoizedSerializedSize);
        }
        for (int i = 0; i < row_.size(); i++) {
          output.writeDoubleNoTag(row_.getDouble(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          dataSize = 8 * getRowList().size();
          size += dataSize;
          if (!getRowList().isEmpty()) {
            size += 1;
            size += com.google.protobuf.CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          rowMemoizedSerializedSize = dataSize;
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.example.proto.Transaction.LargeTransaction.Row)) {
          return super.equals(obj);
        }
        com.example.proto.Transaction.LargeTransaction.Row other = (com.example.proto.Transaction.LargeTransaction.Row) obj;

        if (!getRowList()
            .equals(other.getRowList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getRowCount() > 0) {
          hash = (37 * hash) + ROW_FIELD_NUMBER;
          hash = (53 * hash) + getRowList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.example.proto.Transaction.LargeTransaction.Row parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.example.proto.Transaction.LargeTransaction.Row prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code LargeTransaction.Row}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:LargeTransaction.Row)
          com.example.proto.Transaction.LargeTransaction.RowOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.example.proto.Transaction.internal_static_LargeTransaction_Row_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.example.proto.Transaction.internal_static_LargeTransaction_Row_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.example.proto.Transaction.LargeTransaction.Row.class, com.example.proto.Transaction.LargeTransaction.Row.Builder.class);
        }

        // Construct using com.example.proto.Transaction.LargeTransaction.Row.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          row_ = emptyDoubleList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.example.proto.Transaction.internal_static_LargeTransaction_Row_descriptor;
        }

        @java.lang.Override
        public com.example.proto.Transaction.LargeTransaction.Row getDefaultInstanceForType() {
          return com.example.proto.Transaction.LargeTransaction.Row.getDefaultInstance();
        }

        @java.lang.Override
        public com.example.proto.Transaction.LargeTransaction.Row build() {
          com.example.proto.Transaction.LargeTransaction.Row result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.example.proto.Transaction.LargeTransaction.Row buildPartial() {
          com.example.proto.Transaction.LargeTransaction.Row result = new com.example.proto.Transaction.LargeTransaction.Row(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) != 0)) {
            row_.makeImmutable();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.row_ = row_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.example.proto.Transaction.LargeTransaction.Row) {
            return mergeFrom((com.example.proto.Transaction.LargeTransaction.Row)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.example.proto.Transaction.LargeTransaction.Row other) {
          if (other == com.example.proto.Transaction.LargeTransaction.Row.getDefaultInstance()) return this;
          if (!other.row_.isEmpty()) {
            if (row_.isEmpty()) {
              row_ = other.row_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRowIsMutable();
              row_.addAll(other.row_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.example.proto.Transaction.LargeTransaction.Row parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.example.proto.Transaction.LargeTransaction.Row) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.Internal.DoubleList row_ = emptyDoubleList();
        private void ensureRowIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            row_ = mutableCopy(row_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated double row = 1;</code>
         * @return A list containing the row.
         */
        public java.util.List<java.lang.Double>
            getRowList() {
          return ((bitField0_ & 0x00000001) != 0) ?
                   java.util.Collections.unmodifiableList(row_) : row_;
        }
        /**
         * <code>repeated double row = 1;</code>
         * @return The count of row.
         */
        public int getRowCount() {
          return row_.size();
        }
        /**
         * <code>repeated double row = 1;</code>
         * @param index The index of the element to return.
         * @return The row at the given index.
         */
        public double getRow(int index) {
          return row_.getDouble(index);
        }
        /**
         * <code>repeated double row = 1;</code>
         * @param index The index to set the value at.
         * @param value The row to set.
         * @return This builder for chaining.
         */
        public Builder setRow(
            int index, double value) {
          ensureRowIsMutable();
          row_.setDouble(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double row = 1;</code>
         * @param value The row to add.
         * @return This builder for chaining.
         */
        public Builder addRow(double value) {
          ensureRowIsMutable();
          row_.addDouble(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double row = 1;</code>
         * @param values The row to add.
         * @return This builder for chaining.
         */
        public Builder addAllRow(
            java.lang.Iterable<? extends java.lang.Double> values) {
          ensureRowIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, row_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated double row = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearRow() {
          row_ = emptyDoubleList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:LargeTransaction.Row)
      }

      // @@protoc_insertion_point(class_scope:LargeTransaction.Row)
      private static final com.example.proto.Transaction.LargeTransaction.Row DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.example.proto.Transaction.LargeTransaction.Row();
      }

      public static com.example.proto.Transaction.LargeTransaction.Row getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Row>
          PARSER = new com.google.protobuf.AbstractParser<Row>() {
        @java.lang.Override
        public Row parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Row(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Row> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Row> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.example.proto.Transaction.LargeTransaction.Row getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int MATRIX_FIELD_NUMBER = 2;
    private java.util.List<com.example.proto.Transaction.LargeTransaction.Row> matrix_;
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.proto.Transaction.LargeTransaction.Row> getMatrixList() {
      return matrix_;
    }
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.proto.Transaction.LargeTransaction.RowOrBuilder> 
        getMatrixOrBuilderList() {
      return matrix_;
    }
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    @java.lang.Override
    public int getMatrixCount() {
      return matrix_.size();
    }
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    @java.lang.Override
    public com.example.proto.Transaction.LargeTransaction.Row getMatrix(int index) {
      return matrix_.get(index);
    }
    /**
     * <code>repeated .LargeTransaction.Row matrix = 2;</code>
     */
    @java.lang.Override
    public com.example.proto.Transaction.LargeTransaction.RowOrBuilder getMatrixOrBuilder(
        int index) {
      return matrix_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < matrix_.size(); i++) {
        output.writeMessage(2, matrix_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < matrix_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, matrix_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.proto.Transaction.LargeTransaction)) {
        return super.equals(obj);
      }
      com.example.proto.Transaction.LargeTransaction other = (com.example.proto.Transaction.LargeTransaction) obj;

      if (getId()
          != other.getId()) return false;
      if (!getMatrixList()
          .equals(other.getMatrixList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getMatrixCount() > 0) {
        hash = (37 * hash) + MATRIX_FIELD_NUMBER;
        hash = (53 * hash) + getMatrixList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Transaction.LargeTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.LargeTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.proto.Transaction.LargeTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.proto.Transaction.LargeTransaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LargeTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LargeTransaction)
        com.example.proto.Transaction.LargeTransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.proto.Transaction.internal_static_LargeTransaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.proto.Transaction.internal_static_LargeTransaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.proto.Transaction.LargeTransaction.class, com.example.proto.Transaction.LargeTransaction.Builder.class);
      }

      // Construct using com.example.proto.Transaction.LargeTransaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMatrixFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (matrixBuilder_ == null) {
          matrix_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          matrixBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.proto.Transaction.internal_static_LargeTransaction_descriptor;
      }

      @java.lang.Override
      public com.example.proto.Transaction.LargeTransaction getDefaultInstanceForType() {
        return com.example.proto.Transaction.LargeTransaction.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.proto.Transaction.LargeTransaction build() {
        com.example.proto.Transaction.LargeTransaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.proto.Transaction.LargeTransaction buildPartial() {
        com.example.proto.Transaction.LargeTransaction result = new com.example.proto.Transaction.LargeTransaction(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        if (matrixBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            matrix_ = java.util.Collections.unmodifiableList(matrix_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.matrix_ = matrix_;
        } else {
          result.matrix_ = matrixBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.proto.Transaction.LargeTransaction) {
          return mergeFrom((com.example.proto.Transaction.LargeTransaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.proto.Transaction.LargeTransaction other) {
        if (other == com.example.proto.Transaction.LargeTransaction.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (matrixBuilder_ == null) {
          if (!other.matrix_.isEmpty()) {
            if (matrix_.isEmpty()) {
              matrix_ = other.matrix_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMatrixIsMutable();
              matrix_.addAll(other.matrix_);
            }
            onChanged();
          }
        } else {
          if (!other.matrix_.isEmpty()) {
            if (matrixBuilder_.isEmpty()) {
              matrixBuilder_.dispose();
              matrixBuilder_ = null;
              matrix_ = other.matrix_;
              bitField0_ = (bitField0_ & ~0x00000001);
              matrixBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMatrixFieldBuilder() : null;
            } else {
              matrixBuilder_.addAllMessages(other.matrix_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.proto.Transaction.LargeTransaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.proto.Transaction.LargeTransaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.example.proto.Transaction.LargeTransaction.Row> matrix_ =
        java.util.Collections.emptyList();
      private void ensureMatrixIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          matrix_ = new java.util.ArrayList<com.example.proto.Transaction.LargeTransaction.Row>(matrix_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Transaction.LargeTransaction.Row, com.example.proto.Transaction.LargeTransaction.Row.Builder, com.example.proto.Transaction.LargeTransaction.RowOrBuilder> matrixBuilder_;

      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public java.util.List<com.example.proto.Transaction.LargeTransaction.Row> getMatrixList() {
        if (matrixBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matrix_);
        } else {
          return matrixBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public int getMatrixCount() {
        if (matrixBuilder_ == null) {
          return matrix_.size();
        } else {
          return matrixBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public com.example.proto.Transaction.LargeTransaction.Row getMatrix(int index) {
        if (matrixBuilder_ == null) {
          return matrix_.get(index);
        } else {
          return matrixBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder setMatrix(
          int index, com.example.proto.Transaction.LargeTransaction.Row value) {
        if (matrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatrixIsMutable();
          matrix_.set(index, value);
          onChanged();
        } else {
          matrixBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder setMatrix(
          int index, com.example.proto.Transaction.LargeTransaction.Row.Builder builderForValue) {
        if (matrixBuilder_ == null) {
          ensureMatrixIsMutable();
          matrix_.set(index, builderForValue.build());
          onChanged();
        } else {
          matrixBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder addMatrix(com.example.proto.Transaction.LargeTransaction.Row value) {
        if (matrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatrixIsMutable();
          matrix_.add(value);
          onChanged();
        } else {
          matrixBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder addMatrix(
          int index, com.example.proto.Transaction.LargeTransaction.Row value) {
        if (matrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatrixIsMutable();
          matrix_.add(index, value);
          onChanged();
        } else {
          matrixBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder addMatrix(
          com.example.proto.Transaction.LargeTransaction.Row.Builder builderForValue) {
        if (matrixBuilder_ == null) {
          ensureMatrixIsMutable();
          matrix_.add(builderForValue.build());
          onChanged();
        } else {
          matrixBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder addMatrix(
          int index, com.example.proto.Transaction.LargeTransaction.Row.Builder builderForValue) {
        if (matrixBuilder_ == null) {
          ensureMatrixIsMutable();
          matrix_.add(index, builderForValue.build());
          onChanged();
        } else {
          matrixBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder addAllMatrix(
          java.lang.Iterable<? extends com.example.proto.Transaction.LargeTransaction.Row> values) {
        if (matrixBuilder_ == null) {
          ensureMatrixIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, matrix_);
          onChanged();
        } else {
          matrixBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder clearMatrix() {
        if (matrixBuilder_ == null) {
          matrix_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          matrixBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public Builder removeMatrix(int index) {
        if (matrixBuilder_ == null) {
          ensureMatrixIsMutable();
          matrix_.remove(index);
          onChanged();
        } else {
          matrixBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public com.example.proto.Transaction.LargeTransaction.Row.Builder getMatrixBuilder(
          int index) {
        return getMatrixFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public com.example.proto.Transaction.LargeTransaction.RowOrBuilder getMatrixOrBuilder(
          int index) {
        if (matrixBuilder_ == null) {
          return matrix_.get(index);  } else {
          return matrixBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public java.util.List<? extends com.example.proto.Transaction.LargeTransaction.RowOrBuilder> 
           getMatrixOrBuilderList() {
        if (matrixBuilder_ != null) {
          return matrixBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matrix_);
        }
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public com.example.proto.Transaction.LargeTransaction.Row.Builder addMatrixBuilder() {
        return getMatrixFieldBuilder().addBuilder(
            com.example.proto.Transaction.LargeTransaction.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public com.example.proto.Transaction.LargeTransaction.Row.Builder addMatrixBuilder(
          int index) {
        return getMatrixFieldBuilder().addBuilder(
            index, com.example.proto.Transaction.LargeTransaction.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .LargeTransaction.Row matrix = 2;</code>
       */
      public java.util.List<com.example.proto.Transaction.LargeTransaction.Row.Builder> 
           getMatrixBuilderList() {
        return getMatrixFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.proto.Transaction.LargeTransaction.Row, com.example.proto.Transaction.LargeTransaction.Row.Builder, com.example.proto.Transaction.LargeTransaction.RowOrBuilder> 
          getMatrixFieldBuilder() {
        if (matrixBuilder_ == null) {
          matrixBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.proto.Transaction.LargeTransaction.Row, com.example.proto.Transaction.LargeTransaction.Row.Builder, com.example.proto.Transaction.LargeTransaction.RowOrBuilder>(
                  matrix_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          matrix_ = null;
        }
        return matrixBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LargeTransaction)
    }

    // @@protoc_insertion_point(class_scope:LargeTransaction)
    private static final com.example.proto.Transaction.LargeTransaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.proto.Transaction.LargeTransaction();
    }

    public static com.example.proto.Transaction.LargeTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LargeTransaction>
        PARSER = new com.google.protobuf.AbstractParser<LargeTransaction>() {
      @java.lang.Override
      public LargeTransaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LargeTransaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LargeTransaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LargeTransaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.proto.Transaction.LargeTransaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmallTransaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmallTransaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MediumTransaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MediumTransaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LargeTransaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LargeTransaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LargeTransaction_Row_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LargeTransaction_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021transaction.proto\",\n\020SmallTransaction\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004data\030\002 \001(\005\"-\n\021MediumTrans" +
      "action\022\n\n\002id\030\001 \001(\005\022\014\n\004data\030\002 \003(\014\"Y\n\020Larg" +
      "eTransaction\022\n\n\002id\030\001 \001(\005\022%\n\006matrix\030\002 \003(\013" +
      "2\025.LargeTransaction.Row\032\022\n\003Row\022\013\n\003row\030\001 " +
      "\003(\0012>\n\nSquareGRPC\0220\n\006Square\022\021.SmallTrans" +
      "action\032\021.SmallTransaction\"\0002I\n\nFilterGRP" +
      "C\022;\n\017GrayscaleFilter\022\022.MediumTransaction" +
      "\032\022.MediumTransaction\"\0002F\n\014MatrixOpGRPC\0226" +
      "\n\nMultiplier\022\021.LargeTransaction\032\021.LargeT" +
      "ransaction(\0010\001B\034\n\021com.example.protoZ\007.;p" +
      "rotob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SmallTransaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmallTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmallTransaction_descriptor,
        new java.lang.String[] { "Id", "Data", });
    internal_static_MediumTransaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MediumTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MediumTransaction_descriptor,
        new java.lang.String[] { "Id", "Data", });
    internal_static_LargeTransaction_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LargeTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LargeTransaction_descriptor,
        new java.lang.String[] { "Id", "Matrix", });
    internal_static_LargeTransaction_Row_descriptor =
      internal_static_LargeTransaction_descriptor.getNestedTypes().get(0);
    internal_static_LargeTransaction_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LargeTransaction_Row_descriptor,
        new java.lang.String[] { "Row", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
